# -*- coding: utf-8 -*-
"""Copy of bayes_suspect.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sPBgQPLm_2AzCFBlzrhks_RLyo8R0k6r
"""

"""My Bayes Suspect Clever Function"""

import scipy
from sklearn.preprocessing import StandardScaler
import scipy.stats
from statsmodels.distributions.empirical_distribution import ECDF

def fvlikelihood (df,a,value,interval,min,b='NULL'):    
    if b == 'NULL':
        return [len(df),scipy.stats.gaussian_kde(df[a]).integrate_box_1d((1-interval)*df[a].iloc[value],(1+interval)*df[a].iloc[value])]
    else:    
        if len(df[(df[a]<df[a].iloc[value]*(1+interval))&(df[a]>df[a].iloc[value]*(1-interval))])<=min:
            return [0,0]
        else:
            return [len(df[(df[a]<df[a].iloc[value]*(1+interval))&(df[a]>df[a].iloc[value]*(1-interval))]),
            scipy.stats.gaussian_kde(df[(df[a]<df[a].iloc[value]*(1+interval))&(df[a]>df[a].iloc[value]*(1-interval))][b]).integrate_box_1d((1-interval)*df[b].iloc[value],(1+interval)*df[b].iloc[value])]
